# UFS_UTILS test workflow.
#
# Check different versions of the NCEPLIBS libraries that are used by UFS_UTILS.
#
# Ed Hartnett 12/13/22
name: Linux_versions 
on:
  push:
    branches:
    - develop
    paths-ignore:
    - README.md
  pull_request:
    branches:
    - develop
    paths-ignore:
    - README.md

defaults:
  run:
    shell: bash -exo pipefail {0}

jobs:
  Linux_versions:
    runs-on: ubuntu-latest
    env:
      FC: mpifort
      CC: mpicc
      FCFLAGS: -fallow-argument-mismatch
    strategy:
      fail-fast: true
      matrix:
        esmf_version: [8_2_0, 8.3.0, 8.4.0]
        bacio_version: [2.4.1]
        g2_version: [3.4.3]
        sp_version: [2.3.3]
        ip_version: [3.3.3]
        w3nco_version: [2.4.0]
        nemsio_version: [2.5.0]
        sfcio_version: [1.4.0]
        sigio_version: [2.3.0]
        
    steps:

    - name: install-dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libpng-dev zlib1g-dev libjpeg-dev libmpich-dev
        sudo apt-get install libnetcdf-dev libnetcdff-dev netcdf-bin pkg-config
        sudo apt-get install autoconf automake libtool
        
      id: cache-esmf
      uses: actions/cache@v2
      with:
        path: ~/esmf
        key: Linux_versions-esmf-${{ matrix.esmf_version }}-${{ runner.os }}

    - name: build-esmf
      if: steps.cache-esmf.outputs.cache-hit != 'true'
      run: |
        pushd ~
        if [[ ${{ matrix.esmf_version }} == "8_2_0" ]]; then
          wget https://github.com/esmf-org/esmf/archive/ESMF_${{ matrix.esmf_version }}.tar.gz &> /dev/null
          tar zxf ESMF_${{ matrix.esmf_version }}.tar.gz
          cd esmf-ESMF_${{ matrix.esmf_version }}
          export ESMF_DIR=~/esmf-ESMF_${{ matrix.esmf_version }}
        else
          wget https://github.com/esmf-org/esmf/archive/refs/tags/v${{ matrix.esmf_version }}.tar.gz &> /dev/null
          ls -l
          tar zxf v${{ matrix.esmf_version }}.tar.gz          
          cd esmf-${{ matrix.esmf_version }}
          export ESMF_DIR=~/esmf-${{ matrix.esmf_version }}
        fi
        export ESMF_COMM=mpich3
        export ESMF_INSTALL_BINDIR=bin
        export ESMF_INSTALL_LIBDIR=lib
        export ESMF_INSTALL_MODDIR=mod
        export ESMF_COMPILER=gfortran
        export ESMF_INSTALL_PREFIX=~/esmf
        export ESMF_NETCDF=split
        export ESMF_NETCDF_INCLUDE=/usr/include
        export ESMF_NETCDF_LIBPATH=/usr/x86_64-linux-gnu
        export ESMF_PIO=OFF
        export ESMF_MOAB=OFF
        export ESMF_ARRAY_LITE=TRUE
        make -j2
        make install

