# UFS_UTILS test workflow.
#
# Check different versions of the NCEPLIBS libraries that are used by UFS_UTILS.
#
# Ed Hartnett 12/13/22
name: Linux_versions 
on:
  push:
    branches:
    - develop
    paths-ignore:
    - README.md
  pull_request:
    branches:
    - develop
    paths-ignore:
    - README.md

defaults:
  run:
    shell: bash -exo pipefail {0}

jobs:
  Linux_versions:
    runs-on: ubuntu-latest
    env:
      FC: mpifort
      CC: mpicc
      FCFLAGS: -fallow-argument-mismatch
    strategy:
      fail-fast: true
      matrix:
        esmf_version: [8_2_0, 8.3.0, 8.4.0]
        bacio_version: [2.4.1]
        g2_version: [3.4.3]
        sp_version: [2.3.3]
        ip_version: [3.3.3]
        w3nco_version: [2.4.0]
        nemsio_version: [2.5.0]
        sfcio_version: [1.4.0]
        sigio_version: [2.3.0]
        
    steps:

    - name: install-dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libpng-dev zlib1g-dev libjpeg-dev libmpich-dev
        sudo apt-get install libnetcdf-dev libnetcdff-dev netcdf-bin pkg-config
        sudo apt-get install autoconf automake libtool
        
