name: GCC Linux Build and Test
on: [push, pull_request, workflow_dispatch]

jobs:
  ufs_utils:
    runs-on: ubuntu-24.04
    container: ghcr.io/noaa-emc/ci-common-build-cache/ufs-utils-ubuntu-24.04-gcc-13-mpich-x:latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
            path: ufs_utils
            submodules: recursive

      - name: build
        run: |
          . /entrypoint.sh
          export CC=mpicc
          export FC=mpif90
          cd ufs_utils
          cmake -S . -B build -DCMAKE_INSTALL_PREFIX=install
          cmake --build build -j4 VERBOSE=1
          cmake --install build

      - name: ctest
        run: |
          cd ufs_utils
          ctest --test-dir build --verbose --rerun-failed --output-on-failure
